name: decompression-download
on:
  push:
    branches: [ main ]
    paths:
      - 'decompression-list.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 安装环境
      - name: Install Enviroment
        run: |
          sudo apt-get update
          sudo apt-get install unar
          npm install
          mkdir Offline
          node fetchtracker.js
          
      # 下载
      - name: Download
        run: |
          echo "开始下载："
          cat decompression-list.txt
          aria2c --conf-path=aria2.conf --header="Cookie: ${{ secrets.EX_COOKIES }}" -i decompression-list.txt
          
      # 解压
      - name: Decompression
        run: |
          cd Offline
          echo "开始解压："
          ls | egrep '\.(rar|zip)'
          echo ""
          ls | egrep '\.(rar|zip)' | xargs -d '\n' -n1 -i unar "{}"
          
      # 上传
      - name: Upload
        run: |
          node upload.js "${{ secrets.URL }}" "${{ secrets.USERNAME }}" "${{ secrets.PASSWORD }}" decompression
