name: initialize-database
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 安装环境
      - name: Install Environment
        run: |
          npm install

      # 同步数据库
      - name: Sychronize
        run: |
          node initialize-database.js
        env:
          QUEUE_DD_URL: ${{ secrets.URL }}
          QUEUE_DD_USERNAME: ${{ secrets.USERNAME }}
          QUEUE_DD_PASSWORD: ${{ secrets.PASSWORD }}
          QUEUE_DB_URL: ${{ secrets.DB_URL }}
          QUEUE_DB_APIKEY: ${{ secrets.DB_APIKEY }}
