name: offline-download
on:
  push:
    branches: [ main ]
    paths:
      - 'list.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 安装环境
      - name: Install Aria2
        run: |
          sudo apt-get update
          sudo apt-get install aria2
          npm install
          node fetchtracker.js

      # 检查任务队列
      - name: Queue Check
        run: |
          node queue-check.js "${{ github.repository }}" "${{ secrets.TOKEN }}" "${{ github.workflow }}" "${{ github.event.inputs.type }}" "${{ github.event.inputs.list }}"

      # 下载
      - name: Download
        run: |
          echo "开始下载："
          cat list.txt
          aria2c --conf-path=aria2.conf -i list.txt

      # 上传
      - name: Upload
        run: |
          node upload.js "${{ secrets.URL }}" "${{ secrets.USERNAME }}" "${{ secrets.PASSWORD }}"

      # 执行队列剩余任务
      - name: Queue Pop
        run: |
          node queue-pop.js "${{ github.repository }}" "${{ secrets.TOKEN }}" "${{ secrets.TOKEN }}" 
