# This is a basic workflow to help you get started with Actions

name: offline-download

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 准备环境
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 安装aria2
      - name: Install Aria2
        run: |
          sudo apt-get update
          sudo apt-get install aria2

      # 下载
      - name: Download
        run: |
          aria2c "https://i1.hdslb.com/bfs/face/e3df1d12619fee10b471fc787be4372a09ee6b03.jpg@128w_128h_1o.webp"
          ls

      # 上传
      - name: upload
        run: |
          npm install
          node upload.js "${{ secrets.URL }}" "${{ secrets.USERNAME }}" "${{ secrets.PASSWORD }}"
