name: offline-download
on:
#   push:
#     branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 安装aria2
      - name: Install Aria2
        run: |
          sudo apt-get update
          sudo apt-get install aria2
          node fetchtracker.js

      # 下载
      - name: Download
        run: |
          aria2c --conf-path=aria2.conf -i list.txt

      # 安装上传环境
      - name: NPM Install
        run: |
          npm install

      # 上传
      - name: Upload
        run: |
          node upload.js "${{ secrets.URL }}" "${{ secrets.USERNAME }}" "${{ secrets.PASSWORD }}"
